# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'peerbridge-ios' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for peerbridge-ios
  pod 'SwiftyRSA'
  pod 'SwiftLint'
  pod 'SQLite.swift', '~> 0.12.0'
end

target 'peerbridge-ios-tests' do 
 # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for peerbridge-ios-tests
  pod 'SwiftyRSA'
  pod 'SwiftLint'
  pod 'SQLite.swift', '~> 0.12.0'
end